CREATE DATABASE MYDB;
USE MYDB;

CREATE TABLE EMPLOYEE(
	  EMP_ID INT,
      FIRST_NAME VARCHAR(30),
      LAST_NAME VARCHAR(30),
      EMAIL_ID VARCHAR(30),
      PHN_NO VARCHAR(20),
      HOURLY_PAY DECIMAL(5,2),
      HIRED_DATE DATE
);

SELECT * FROM EMPLOYEE;

CREATE TABLE STUDENTS(
      STU_ID INT,
      STU_NAME VARCHAR(30),
      STU_DEPARTMENT VARCHAR(20),
      STU_AGE INT,
      STU_GPA DECIMAL(2,1),
      STU_ATTENDANCE DECIMAL(4,2)
);

SELECT * FROM STUDENTS;

CREATE TABLE PRODUCT(
      PRO_ID INT,
      PRO_NAME VARCHAR(20),
      PRO_QUANTITY_AVAILABLE VARCHAR(15),
      PRO_PRICE DECIMAL(7,2)
);

SELECT * FROM PRODUCT;

ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR(100);

ALTER TABLE EMPLOYEE
ADD DEPARTMENT VARCHAR(50);

ALTER TABLE EMPLOYEE
RENAME COLUMN HOURLY_PAY TO SALARY_PER_HOUR;

ALTER TABLE EMPLOYEE
MODIFY COLUMN FIRST_NAME VARCHAR(100);

ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_ID VARCHAR(10);

ALTER TABLE EMPLOYEE
MODIFY DEPARTMENT VARCHAR(50)
AFTER LAST_NAME;

ALTER TABLE EMPLOYEE
MODIFY EMAIL VARCHAR(100)
FIRST;

ALTER TABLE EMPLOYEE
DROP COLUMN DEPARTMENT;

ALTER TABLE EMPLOYEE
ADD AGE INT,
ADD CITY VARCHAR(30);

ALTER TABLE EMPLOYEE
MODIFY COLUMN HIRED_DATE DATETIME;

SELECT * FROM EMPLOYEE;
SELECT * FROM PRODUCT;
SELECT * FROM STUDENTS;

