--DATABASE CREATED
CREATE DATABASE OFFICE_DB;

--DROP THE DATABASE
DROP DATABASE OFFICE_DB;

--DATABASE CREATED
CREATE DATABASE OFFICE_DB;

--SET AS DEFAULT SCHEMA
USE OFFICE_DB;

--CREATE TABLE
CREATE TABLE EMPLOYEE(
	 EMP_ID INT,
     EMP_NAME VARCHAR(20),
     EMP_AGE INT,
     EMP_SALARY DECIMAL(7,2)
     );
     
--DISPLAY THE TABLE
SELECT * FROM EMPLOYEE;

--RENAME THE TABLE
RENAME TABLE EMPLOYEE TO EMPLOYEES;

--DROP THE TABLE
DROP TABLE EMPLOYEES;

--CREATE TABLE
CREATE TABLE EMPLOYEE(
	 EMP_ID INT,
     EMP_NAME VARCHAR(20),
     EMP_AGE INT,
     EMP_SALARY DECIMAL(7,2),
     EMP_PHN_NO VARCHAR(20)
     );

--ALTER THE TABLE
--ADD A NEW COLUMN
ALTER TABLE EMPLOYEE
ADD COLUMN EMP_MAIL VARCHAR(50);

--RENAME A COLUMN
ALTER TABLE EMPLOYEE
RENAME COLUMN EMP_MAIL TO EMP_MAIL_ID;

--MODIFY A COLUMN
--CHANGE THE DATATYPE
ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_SALARY INT;

--CHANGE DATATYPE SIZE
ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_MAIL_ID VARCHAR(30);

--DROP THE COLUMN
ALTER TABLE EMPLOYEE
DROP COLUMN EMP_MAIL_ID;

--CHANGING COLUMN POSITION
--AFTER EXISTING COLUMN
ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_ID VARCHAR(20)
AFTER EMP_NAME;

--FIRST COLUMN
ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_ID VARCHAR(20)
FIRST;

--INSERT DATAS
INSERT INTO EMPLOYEE VALUES
(1,'JOHN',23,30000,9345287052),
(2,'DHEENA',25,35000,9922008822),
(3,'PRIYA',28,25000,9865615066),
(4,'RIYA',30,40000,8610745786);

--TRUNCATE TABLE
TRUNCATE TABLE EMPLOYEE;

--INSERT NEW DATA
INSERT INTO EMPLOYEE VALUES
(5,'NITHISH',24,20000,9944557788);

--UPDATE DATA 
UPDATE EMPLOYEE
SET EMP_SALARY = 15000 WHERE EMP_ID = 5;

SELECT * FROM EMPLOYEE;

--DELETE SINGLE DATA
DELETE FROM EMPLOYEE WHERE EMP_ID = 4; 

--READ ONLY MODE(0,1)
ALTER DATABASE OFFICE_DB READ ONLY = 1;

ALTER DATABASE OFFICE_DB READ ONLY = 0;







     
     
