--DATABASE CREATED
CREATE DATABASE EMPLOYEE_DB;

--SET DATABASE DEFAULT
USE EMPLOYEE_DB;

--TABLE CREATED
CREATE TABLE EMPLOYEE(
	 emp_id INT,
     emp_name VARCHAR(50),
     gender VARCHAR(10),
     department VARCHAR(50),
     salary DECIMAL(10,2),
     hire_date DATE,
     city VARCHAR(50)
);

--DATA INSERT TO THE TABLE
INSERT INTO employee VALUES  
(101,'John','Male', 'IT',65000,'2021-01-15','Chennai'), 
(102,'Sarah','Female','HR',45000,'2020-03-10','Bangalore'), 
(103,'David', 'Male','Finance',70000,'2019-07-20', 'Mumbai'), 
(104,'Priya','Female','IT',80000,'2022-02-18','Chennai'), 
(105,'Ahmed','Male','Sales',55000,'2021-09-25','Hyderabad'), 
(106,'Meena','Female', 'HR',50000,'2023-01-05','Delhi'), 
(107,'Raj','Male','IT',90000,'2018-11-12','Bangalore'), 
(108,'Anita','Female','Finance',75000,'2020-08-30', 'Mumbai'), 
(109,'Kumar','Male','Sales',60000,'2022-04-15','Chennai'),
(110,'Fatima','Female', 'IT',85000,'2019-06-22','Hyderabad');

--DISPLAY ALL EMPLOYEES
SELECT * FROM EMPLOYEE;

--DISPLAY EMPLOYEE NAMES AND SALARIES
SELECT EMP_NAME,SALARY FROM EMPLOYEE;

--SHOW EMPLOYEES WORKING IN IT
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'IT';

--SHOW EMPLOYEES EARNING MORE THAN 60000
SELECT * FROM EMPLOYEE
WHERE SALARY > 60000;

--DISPLAY EMPLOYEES FROM CHENNAI
SELECT * FROM EMPLOYEE
WHERE CITY = 'CHENNAI';

--FIND EMPLOYEES HIRED AFTER 2021
SELECT * FROM EMPLOYEE
WHERE YEAR(HIRE_DATE) > 2021;

--DISPLAY EMPLOYEES SORTED BY SALARY
SELECT * FROM EMPLOYEE
WHERE SALARY = 60000;

--FIND THE HIGHEST PAID EMPLOYEE
SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC LIMIT 1;

--FIND THE AVERAGE SALARY
SELECT AVG(SALARY) FROM EMPLOYEE;

--COUNT EMPLOYEES IN EACH DEPARTMENT
SELECT DEPARTMENT, 
COUNT(*) FROM EMPLOYEE
GROUP BY DEPARTMENT;

--DISPLAY DEPARTMENTS HAVING MORE THAN TWO EMPLOYEES
SELECT DEPARTMENT,
COUNT(*) FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*) > 2;

--DISPLAY UNIQUE CITIES
SELECT DISTINCT CITY FROM EMPLOYEE;

--SHOW EMPLOYEES WHOSE NAMES START WITH 'A'
SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE 'A%';

--SHOW EMPLOYEES WITH SALARIES BETWEEN 50000 AND 80000
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 50000 AND 80000;

--DISPLAY THE TOP THREE HIGHEST PAID EMPLOYEES
SELECT * FROM EMPLOYEE 
ORDER BY SALARY DESC LIMIT 3;