--DATABASE CREATED
CREATE DATABASE OFFICE;

--SET DATABSE DEFAULT
USE OFFICE;

--TABLE CREATED
CREATE TABLE Employee(
EmpID INT PRIMARY KEY,
EmpName VARCHAR(50),
Department VARCHAR(30),
Salary DECIMAL(10,2)
);

--DATA INSERT TO TABLE
INSERT INTO Employee VALUES
(101,'Rahul','IT',45000),
(102,'Priya','HR',52000),
(103,'Amit','Finance',60000),
(104,'Sneha','IT',48000),
(105,'John','HR',55000);

--1.Increase Rahul's salary by ₹5000. Do not commit immediately. Verify the result.Rollback
the transaction. What is Rahul's final salary?
START TRANSACTION;
UPDATE EMPLOYEE SET SALARY = SALARY+5000 WHERE EMPID = 101; 
SELECT * FROM EMPLOYEE;
ROLLBACK;
SELECT * FROM EMPLOYEE;

--2.Increase every employees salary by 10%. Commit the transaction. Verify the result?
START TRANSACTION;
UPDATE EMPLOYEE SET SALARY = SALARY * 1.10; 
COMMIT;
SELECT * FROM EMPLOYEE;

--3.Increase Rahul salary by ₹3000. Create SAVEPOINT sp1. Increase Priya's salary by
₹5000. Rollback to sp1. Which employee's salary is rolled back?
START TRANSACTION;
UPDATE EMPLOYEE SET SALARY = SALARY+3000 WHERE EMPID = 101; 
SAVEPOINT SP1;
UPDATE EMPLOYEE SET SALARY = SALARY+5000 WHERE EMPID = 102; 
ROLLBACK;
SELECT * FROM EMPLOYEE;

--4.DELETE HR employees. Rollback. How many HR employees remain?
START TRANSACTION;
DELETE FROM EMPLOYEE WHERE DEPARTMENT = 'HR';
ROLLBACK;
SELECT * FROM EMPLOYEE;

--5. DELETE Finance employees. COMMIT. Then ROLLBACK. Will the Finance employee
return? Explain.
START TRANSACTION;
DELETE FROM EMPLOYEE WHERE DEPARTMENT = 'FINANCE';
COMMIT;
ROLLBACK;
SELECT * FROM EMPLOYEE;


